TAGS = ["theorem", "definition"]

koetzing_config = {
    '\\CalF': "\\mathcal{F}",
		'\\CalX': "\\mathcal{X}",
		'\\bigO': "\\mathcal{O}\\mathclose{\\left(##1\\right)}",
		'\\bigOSymbol': "\\mathcal{O}",
		'\\Bij': "\\mathcal{B}",
		'\\natnum': "\\mathbb{N}",
		'\\integers': "\\mathbb{Z}",
		'\\rationals': "\\mathbb{Q}",
		'\\realnum': "\\mathbb{R}",
		'\\less': "\\lt",
		'\\modulo': "\\; \\operatorname{mod} \\;",
		'\\isom': "\\cong",
		'\\qed': "\\Box",
		'\\set': "\\{##1 \\mid ##2\\}", 
		'\\pot': "\\mathrm{Pot}",
		'\\eqnComment': "\\underset{{\\scriptstyle \\text{##1}}}{##2}",
		'\\ind': "\\mathbb{1}\\mathclose{\\left[##1\\right]}",
		'\\Ew': "\\operatorname{E}\\mathclose{\\left[##1\\right]}",
		'\\Var': "\\operatorname{Var}\\mathclose{\\left[##1\\right]}",
}

command_to_package = {
    '\\textbf': 'amsmath',
    '\\textit': 'amsmath',
    '\\texttt': 'amsmath',
    '\\cite': 'natbib',
    '\\ref': 'hyperref',
    '\\url': 'hyperref',
    '\\includegraphics': 'graphicx',
    '\\caption': 'caption',
    '\\subcaption': 'subcaption',
    '\\item': 'enumitem',
    '\\begin{tabular}': 'tabularx',
    '\\text': 'amsmath',        
    '\\mathbb': 'amsfonts',     
    '\\mathcal': 'mathrsfs',    
    '\\mathrm': '',             
    '\\mathbf': '',             
    '\\mathit': '',             
    '\\mathsf': '',             
    '\\mathtt': '',             
    '\\mathfrak': 'amssymb',    
    '\\mathscr': 'mathrsfs',    
    '\\boldsymbol': 'amsmath',  
    '\\binom': 'amsmath',         
    '\\dfrac': 'amsmath',         
    '\\tfrac': 'amsmath',         
    '\\cfrac': 'amsmath',         
    '\\genfrac': 'amsmath',       
    '\\DeclareMathOperator': 'amsmath',  
    '\\operatorname': 'amsmath',  
    '\\eqref': 'amsmath',         
    '\\textsuperscript': '',      
    '\\textsubscript': 'fixltx2e',
    '\\overset': 'amsmath',       
    '\\underset': 'amsmath',      
    '\\sideset': 'amsmath',       
    '\\stackrel': 'amsmath', 
}

latex_header = """
\\documentclass{article}
\\title{Matheskript}
\\usepackage[a4paper, left=10mm, right=10mm, top=10mm, bottom=10mm]{geometry}\n
"""

latex_footer = """


%% This file is autogenerated by scriptfetch
"""